language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
    - "pip install -r requirements-tests.txt"
# command to run tests
script: nosetests